commit:first commit
Guan-SiYu/game-node-testing pull request #1
Opened 2020-10-14 08:36 UTC by Guan-SiYu

对猜数字游戏api进行单元测试

框架jest+库supertest

2020-10-14 08:48 UTC, vincent-ng requested changes

2020-10-14 08:48 UTC, vincent-ng commented on test/app.test.js
> +		.send('smaller')
这个send是发送给服务器的意思吧？这里应该不用传参数。下同

2020-10-14 08:48 UTC, vincent-ng commented on test/app.test.js
> +		expect(response.status).toBe(200)
状态断言可以直接用supertest的expect方法

2020-10-14 08:48 UTC, vincent-ng commented on test/app.test.js
> +		const response = await request.get('/14')
发过去14可不一定是返回smaller哦

2020-10-14 08:48 UTC, vincent-ng commented on test/app.test.js
> +	it('返回smaller',async done=>{
callback style才需要done
async不需要

2020-10-14 08:48 UTC, vincent-ng commented on router.js
> +})
- params读出来的number是字符串的，需要Number()转成数字类型
- ==过不了eslint，要用===
- equal的时候res.send调用了2次，express会报错，应该return出去

2020-10-14 08:53 UTC, Guan-SiYu commented on test/app.test.js
> +		.send('smaller')
我以为.send('smaller')是判断服务器send 'smaller'....... 😿

2020-10-15 07:19 UTC, vincent-ng requested changes

2020-10-15 07:19 UTC, vincent-ng commented on router.js
> +	if(num==flag)res.json({message:'equal'})
接口格式不能改

2020-10-16 13:25 UTC, merged